Add stub $sdf_annotate function.
Add the $sdf_annotate function infrastructure, and a stub parser
that can parse miniman SDF files.

Signed-off-by: Stephen Williams <steve@icarus.com>

diff --git a/vpi/configure.in b/vpi/configure.in
--- a/vpi/configure.in
+++ b/vpi/configure.in
@@ -15,6 +15,14 @@ then
         exit 1
 fi
 
+AC_CHECK_PROGS(YACC,bison,none)
+if test "$YACC" = "none"
+then
+	echo "*** Error: No suitable bison found. ***"
+        echo "    Please install the 'bison' package."
+        exit 1
+fi
+
 AC_EXEEXT
 AC_SUBST(EXEEXT)
 
